 include:
 - board: seeeduino_xiao_ble
   shield: sirius_dongle
   snippet: studio-rpc-usb-uart
 - board: seeeduino_xiao_ble
   shield: sirius_left
 - board: seeeduino_xiao_ble
   shield: sirius_right
 - board: seeeduino_xiao_ble
   shield: settings_reset
